### ISSUE TITLE
Find a replacement term for 'absolute finality'.

### ISSUE THREAD

**Issue by nathan-at-least** [Electric-Coin-Company/tfl-book#58]
### Suggested Improvement

The current book text says "absolute finality" which is misleading.

When I used that term, I meant "a property of the protocol, excluding out-of-band social coordinated exceptions/modifications". So for example, a protocol with this use of "absolute finality" could still be forked by a sufficient social consensus to revert txns or make other changes.

However, many people who read "absolute finality" are likely to conclude "absolute" means the direct denotation (instead of my custom nuanced usage). With the direct denotational meaning, that would imply that no change, even social consensus, can revert finality. (Which is impossible, but the issue still stands.)

**Comment by daira** [comment]
Suggestions:
* assured finality
* conclusive finality
* definite finality
* strong finality
* settled finality
* strict finality
* resolved finality

**Comment by daira** [comment]
Changed to "assured finality" in #61.
